version: 2

updates:
  - package-ecosystem: npm
    directory: /
    labels:
      - dependabot
    ignore:
      - dependency-name: "*"
      - update-types:
          ["version-update:semver-major", "version-update:semver-minor"]
    schedule:
      interval: weekly
