version: 2

updates:
  - package-ecosystem: npm
    directory: /
    labels:
      - dependabot
    ignore:
      - dependency-name: "*"
      - update-types: ["version-update:semver-patch"]
    schedule:
      interval: weekly
