name: Keep Alive

on:
  schedule:
    - cron: 0 0 1 * *
  workflow_dispatch:

jobs:
  keep-alive:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Update .keepalive
        run: echo $(date +'%s') > .keepalive
      - name: Commit .keepalive
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          if [ -z "$(git status --porcelain)" ]; then
            echo "::error::Error: No changes to commit"
            exit 1
          fi
          git add .
          git commit -m "ci: keep alive workflow run"
          git push origin $(git branch --show-current)
