name: Keep alive

on:
  schedule:
    - cron: 0 0 * * *

jobs:
  keep-alive:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: gautamkrishnar/keepalive-workflow@v1
