name: Sync subscriptions

on:
  workflow_dispatch:
  schedule:
    - cron: '*/5 * * * *'

jobs:
  sync-subscriptions:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - uses: actions/setup-node@v3
        with:
          node-version-file: .node-version
          cache: pnpm
      - run: pnpm install
      - run: pnpm sync
        env:
          GC_CLIENT_EMAIL: ${{ secrets.GC_CLIENT_EMAIL }}
          GC_PRIVATE_KEY: ${{ secrets.GC_PRIVATE_KEY }}
          GMAIL_CLIENT_EMAIL: ${{ secrets.GMAIL_CLIENT_EMAIL }}
          GMAIL_PRIVATE_KEY: ${{ secrets.GMAIL_PRIVATE_KEY }}
