name: Sync Subscriptions

on:
  workflow_dispatch:
  schedule:
    - cron: "* * * * *"

jobs:
  sync-subscriptions:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v4
        with:
          node-version-file: .node-version
          cache: pnpm
      - run: pnpm install
      - run: pnpm sync
        env:
          GC_CLIENT_EMAIL: ${{ secrets.GC_CLIENT_EMAIL }}
          GC_PRIVATE_KEY: ${{ secrets.GC_PRIVATE_KEY }}
          GMAIL_CLIENT_EMAIL: ${{ secrets.GMAIL_CLIENT_EMAIL }}
          GMAIL_PRIVATE_KEY: ${{ secrets.GMAIL_PRIVATE_KEY }}
          GMAIL2_CLIENT_EMAIL: ${{ secrets.GMAIL2_CLIENT_EMAIL }}
          GMAIL2_PRIVATE_KEY: ${{ secrets.GMAIL2_PRIVATE_KEY }}
          SUBSCRIPTIONS: ${{ vars.SUBSCRIPTIONS }}
          FOOTBALL_CALENDAR_ID: ${{ secrets.FOOTBALL_CALENDAR_ID }}
          FOOTBALL_SUBSCRIPTION_URL: ${{ vars.FOOTBALL_SUBSCRIPTION_URL }}
          FOOTBALL_USER: ${{ vars.FOOTBALL_USER }}
          HOLIDAYS_CALENDAR_ID: ${{ secrets.HOLIDAYS_CALENDAR_ID }}
          HOLIDAYS_SUBSCRIPTION_URL: ${{ vars.HOLIDAYS_SUBSCRIPTION_URL }}
          HOLIDAYS_USER: ${{ vars.HOLIDAYS_USER }}
          LEWAGON_CALENDAR_ID: ${{ secrets.LEWAGON_CALENDAR_ID }}
          LEWAGON_SUBSCRIPTION_URL: ${{ vars.LEWAGON_SUBSCRIPTION_URL }}
          LEWAGON_USER: ${{ vars.LEWAGON_USER }}
