name: Validate commits

on: [push, pull_request]

jobs:
  validate-commits:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: 8.10.5
      - uses: actions/setup-node@v4
        with:
          node-version-file: .node-version
          cache: pnpm
      - name: Install dependencies
        run: |
          pnpm install
          echo "./node_modules/.bin" >> $GITHUB_PATH
      - name: Run commitlint
        if: github.event_name == 'pull_request'
        run: |
          if [[ "${{ github.actor }}" =~ "dependabot[bot]" ]]; then
            echo "::info ::Skipping commitlint on package bump"
            exit 0
          fi
          commitlint --from ${{ github.event.pull_request.head.sha }}~${{ github.event.pull_request.commits }} --to ${{ github.event.pull_request.head.sha }} --verbose
      - name: Run linters
        run: pnpm lint
