name: Validate commits

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - uses: actions/setup-node@v3
        with:
          node-version-file: .node-version
          cache: pnpm
      - name: Install dependencies
        run: |
          pnpm install
          echo "./node_modules/.bin" >> $GITHUB_PATH
      - name: Run commitlint
        if: github.event_name == 'push'
        run: |
          if [[ ${{ github.event.forced }} == true ]]; then
            echo "::warning ::Validating last commit only on force push"
            commitlint --from HEAD~1 --to HEAD --verbose
            exit $?
          fi
          if [[ ${{ github.event.before }} == 0000000000000000000000000000000000000000 ]]; then
            echo "::warning ::Validating last commit only on branch ${{ github.ref_name }}"
            commitlint --from HEAD~1 --to HEAD --verbose
            exit $?
          fi
          commitlint --from ${{ github.event.before }} --to ${{ github.event.after }} --verbose
      - name: Validate PR commits
        if: github.event_name == 'pull_request'
        run: |
          if [[ "${{ github.actor }}" =~ "dependabot[bot]" ]]; then
            echo "::info ::Skipping commitlint on package bump"
            exit 0
          fi
          commitlint --from ${{ github.event.pull_request.head.sha }}~${{ github.event.pull_request.commits }} --to ${{ github.event.pull_request.head.sha }} --verbose
      - name: Run linters
        run: pnpm lint:code
